import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '@styles/Home.module.scss';
import { TITLE_BASE } from '@/utils/constants';
import nature from 'public/img/nature.jpeg';
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{TITLE_BASE}votre organisateur évènementiel</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>Mariage à thème et sur mesure</h1>
      <p className={styles.description}>Construisons ensemble votre projet</p>
      <div className="images">
        <Image
          alt="nature"
          src={nature}
          layout="fill"
          sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              33vw"
        />
      </div>
      <div className="youtube-iframe-video">
        <iframe
          width="560"
          height="315"
          src="https://www.youtube.com/embed/9IOBFl5SQVM?controls=0"
          title="YouTube video player"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        ></iframe>
      </div>
    </div>
  );
};

export default Home;
